import { readFile, writeFile } from 'node:fs/promises'
const source = new URL('../src/browser/', import.meta.url)
const css = await readFile(new URL('style.css', source), 'utf8')
const parts = await Promise.all(['conversation.js', 'manager.js', 'views.js', 'entry.js'].map(name => readFile(new URL(name, source), 'utf8')))
await writeFile(new URL('../src/client.js', import.meta.url), `// Generated by scripts/build-client.mjs; edit src/browser instead.\nwindow.__ModuleLoader__.load({\n  id: 'dsh-ssh-workspaces',\n  factory: require => {\n    const React = require('react'), h = React.createElement\n    const styles = ${JSON.stringify(css)}\n${parts.join('\n')}\n  }\n})\n`)
